apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: jwt-auth-plugin, global-rate-limit
spec:
  rules:
  - http:
      paths:
      - path: /test-echo
        pathType: Prefix
        backend:
          service:
            name: echo-service
            port:
              number: 80