resources:
  - ../../base
  - ingress-patch.yaml

namespace: application

replicas:
  - name: echo-service
    count: 3

# Cambiamo il messaggio del container solo per l'ambiente locale
patches:
  - target:
      kind: Deployment
      name: echo-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["-text=Risposta dal TEST LOCALE tramite KONG"]